Created simple CRUD app using Spring
MaxSasha/Task_2 pull request #1
Opened 2020-11-10 13:35 UTC by MaxSasha

2020-11-11 12:31 UTC, AN0NIM17 commented on src/main/java/com/maxsasha/api/dto/UserDto.java
> +@Setter
you can replace this strings with `@Data`, same

2020-11-11 12:31 UTC, AN0NIM17 commented on src/main/java/com/maxsasha/api/dto/UserDto.java
> +	@Setter(AccessLevel.NONE)
remove this, sometimes this setter is used

2020-11-11 12:31 UTC, AN0NIM17 commented on src/main/java/com/maxsasha/api/transformer/UserTransformer.java
> +	}
Try `return users.stream().map(m -> transform(m)).collect(Collectors.toList());`
Examples: https://www.geeksforgeeks.org/stream-map-java-examples/

2020-11-11 12:31 UTC, AN0NIM17 commented on src/main/java/com/maxsasha/entity/User.java
> +@Setter
You can use `@Data`

2020-11-11 12:31 UTC, AN0NIM17 commented on src/main/java/com/maxsasha/entity/User.java
> +	@Setter(AccessLevel.NONE)
remove this

2020-11-11 12:31 UTC, AN0NIM17 commented on src/main/java/com/maxsasha/service/UserService.java
> +	private final UserRepository dbActions;
I recommend rename `dbActions` to `userRepository`

2020-11-13 09:59 UTC, koropatva requested changes

2020-11-13 09:59 UTC, koropatva commented on src/main/java/com/maxsasha/api/controller/UserController.java
> +		log.info("Request to get users successfully completed. Users count:{}", users.size());
remove this log. It doesn't make sence

2020-11-13 09:59 UTC, koropatva commented on src/main/java/com/maxsasha/api/controller/UserController.java
> +		List<UserDto> users = UserTransformer.transform(service.getUsers());
return result, don't save it to variabel

2020-11-13 09:59 UTC, koropatva commented on src/main/java/com/maxsasha/api/controller/UserController.java
> +		log.info("Request to create successfuly completed with info: name:{} , email:{}", userDto.getName(),userDto.getEmail());
remove it

2020-11-13 09:59 UTC, koropatva commented on src/main/java/com/maxsasha/api/controller/UserController.java
> +		log.info("Received request to create user");
Add logging of userDTO info on log message

2020-11-13 09:59 UTC, koropatva commented on src/main/java/com/maxsasha/api/controller/UserController.java
> +		log.info("Received request to update user id:{}", id);
WTF? Rewrite this method. You don't need to check if user is present or not and do all that actions

2020-11-13 09:59 UTC, koropatva commented on src/main/java/com/maxsasha/api/controller/UserController.java
> +		log.info("Request to delete successfuly completed");
Remove this log

2020-11-13 09:59 UTC, koropatva commented on src/main/java/com/maxsasha/api/controller/UserController.java
> +	@GetMapping("/users")
move `users` uri to `RequestMapping` level, as you use it in all API's

2020-11-13 09:59 UTC, koropatva commented on src/main/java/com/maxsasha/api/controller/UserController.java
> +	public List<UserDto> getUsers() {
You can't work with objects, selecting all records. you should use pagination for it. Rewrite it with pagination

2020-11-13 09:59 UTC, koropatva commented on src/main/java/com/maxsasha/api/transformer/UserTransformer.java
> +	{
Combination `Ctrl + F5` will format your code. So pls use it on future

2020-11-13 09:59 UTC, koropatva commented on src/main/java/com/maxsasha/entity/User.java
> +@Builder
Do you really needs `Builder` for `User` entity?

2020-11-13 09:59 UTC, koropatva commented on src/main/resources/application.properties
> +spring.data.mongodb.auto-index-creation=true
Are you really need all those parameters on property file?

2020-11-16 11:50 UTC, MaxSasha commented on src/main/java/com/maxsasha/entity/User.java
> +@Builder
I don't need it critically, I use it once for `User` and `UserDto` in `UserTransformer`, so I can rewrite my `UserTransformer` methods using class constructors

2020-11-17 13:42 UTC, koropatva requested changes

2020-11-17 13:42 UTC, koropatva commented on src/main/java/com/maxsasha/api/controller/UserController.java
> +		Map<String, Object> response = new HashMap<>();
If you want to return some data structure, you should create object, populate fields and return object. Spring will automatic convert object to JSON using Jackson library

2020-11-17 13:42 UTC, koropatva commented on src/main/java/com/maxsasha/api/controller/UserController.java
>  		log.info("Received request to get users ");
As you put page and size as parameters you should log those data

2020-11-17 13:42 UTC, koropatva commented on src/main/java/com/maxsasha/api/controller/UserController.java
>  	public void create(@RequestBody UserDto userDto) {
When you create something you should return this object that will contains created id, in this way FE will know ID of created object

2020-11-17 13:42 UTC, koropatva commented on src/main/java/com/maxsasha/api/controller/UserController.java
> +		userDto.setId(id);
move the population of id into transformer.

2020-11-17 13:42 UTC, koropatva commented on src/main/java/com/maxsasha/api/controller/UserController.java
> +		UserDto updatedUser = UserTransformer.transform(service.edit(UserTransformer.transform(userDto)));
You don't need to make variable and populate fields for ResponseEntity, just return result and spring will populate those fields in auth way

2020-11-17 13:42 UTC, koropatva commented on src/main/java/com/maxsasha/api/transformer/UserTransformer.java
> +		return new User(dto.getId(),dto.getName(),dto.getEmail());
Use builder for fields population

2020-11-17 13:42 UTC, koropatva commented on src/main/java/com/maxsasha/api/transformer/UserTransformer.java
> +		return new UserDto(user.getId(),user.getName(),user.getEmail());
same here

2020-11-18 10:07 UTC, koropatva requested changes

2020-11-19 08:59 UTC, MaxSasha commented on src/main/java/com/maxsasha/api/transformer/UserTransformer.java
> +@Component
I forgot to remove this annotation

2020-11-20 14:24 UTC, koropatva requested changes

2020-11-20 14:24 UTC, koropatva commented on src/main/java/com/maxsasha/api/controller/UserController.java
> +		return transform(user,user.getId());
You can fetch userId from User on transformer, so add this new method to transform

2020-11-20 14:24 UTC, koropatva commented on src/main/java/com/maxsasha/api/transformer/UserTransformer.java
> +@Component
you have possibility to remove it

2021-01-15 11:19 UTC, koropatva requested changes

2021-01-15 11:19 UTC, koropatva commented on src/main/java/com/maxsasha/api/dto/StudentDto.java
> +	private String address;
?

2021-02-16 12:35 UTC, merged